### ISSUE TITLE
Deprecation message from CSV.jl

### ISSUE THREAD

**Issue by giordano** [alan-turing-institute/MLJBase.jl#11]
[This commit](https://github.com/alan-turing-institute/MLJBase.jl/commit/62bfdbd8f6ddd9ba406954edff27d780e2ddca25) brought back `allowmissing=:none`, but this keyword is deprecated in `CSV.jl` and should not be used at all.  See https://github.com/JuliaData/CSV.jl/pull/395#issuecomment-493992435 which gives an alternative in case you want to make sure there are no missing values in the resulting dataframe

**Comment by ablaom** [comment]
The problem is that columns sometimes get the type `Vector{Union{Missing,T}}` in old versions of CSV, *even when there are no missing values*,  unless you put this keyword in. If you can find a way to ensure this doesn't happen under the older versions of CSV, without the keyword, go ahead and make a PR, thanks.

**Comment by giordano** [comment]
> If you can find a way to ensure this doesn't happen under the older versions of CSV

Just rise the required version of CSV to a more reliable one and get rid of the option?

**Comment by ablaom** [comment]
I'd rather live with the warning than restrict usage of MLJ. For example, in my own day-to-day environment I would not be able to run MLJ with the restriction.

**Comment by giordano** [comment]
The point is that in the current stable version of `CSV` that option doesn't do anything at all, apart from printing a warning.  In the future, that option will be removed and keeping it will error.

**Comment by ablaom** [comment]
Resolved 5e425d1d7df7f5f75eba69b8e3e70c32c1b81c22. Registering new version now.
