### ISSUE TITLE
"The classes are un-ordered" warning when classes are indeed ordered

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJBase.jl#111]
```julia
julia> using MLJ
julia> X, y = @load_crabs;
julia>  y = coerce(y, OrderedFactor);
julia> scitype(y)
AbstractArray{OrderedFactor{2},1}

julia> MLJ.fp(y, y)
┌ Warning: The classes are un-ordered,
│ using: negative='B' and positive='O'.
│ To suppress this warning, consider coercing to OrderedFactor.
└ @ MLJBase ~/Dropbox/Julia7/MLJ/MLJBase/src/measures/confusion_matrix.jl:73
0
```

**Comment by tlienart** [comment]
### Analysis

I can reproduce the bug, it stems from this:

```julia
y = coerce(y, OrderedFactor)
scitype(y)            # AbstractArray{OrderedFactor{2},1}
scitype_union(y) #  Multiclass{2}
```

Note  that I know you've been warning against the use of `scitype_union` but doing the check  with scitype is  actually annoying and I do  just  want to get the "element" scitype (i.e. the `_get_elst` temporary fix suggested in the PR below). 

### Fix

PR #112 a simple fix in dev which does what I was expecting `scitype_union` to do above which fixes the issue.

I guess there's a couple oof options as to  how we can proceed here:

* deprecate `scitype_union` and make it do  what the simple `_get_elst` does in the PR above
* fix  `scitype_union` if the above is a bug
* not do anything and just merge the PR and come back to this  later

**Comment by ablaom** [comment]
As discussed [here](https://github.com/alan-turing-institute/ScientificTypes.jl/issues/48), I believe the offending problem is a bug in CategoricalArrays.

**Comment by ablaom** [comment]
@tlienart Is this resolved by https://github.com/alan-turing-institute/ScientificTypes.jl/pull/54 ?

**Comment by tlienart** [comment]
yes
