### ISSUE TITLE
Add functionality to generate foo data

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJBase.jl#118]
In MLJLinearModels I  coded some stuff to generate data for regression or classification with  some features like

- use seed
- add sparsity
- add outliers
- number of classes
- etc

I feel it could be  good  to just have this live in MLJBase and require people who want to interface with MLJ to try their stuff on that foo data first

thoughts?

**Comment by ablaom** [comment]
Sounds good to me.

**Comment by davidbp** [comment]
I've made a pull request with some tipical datasets. Plan to use it in my own MulticlassPerceptron model as well.

**Comment by tlienart** [comment]
ongoing work in #136 will add some of this; subsequently we can add sparsity or imbalance options

**Comment by tlienart** [comment]
effectively done thanks to @davidbp 's PR #136
