### ISSUE TITLE
Add more info to `metadata_*` docstrings

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJBase.jl#125]
For newcomers the docstring is a bit obscure. The docstrings should:

* specify the arguments with defaults
* point to the MLJ doc where we talk about metadata

**Comment by ablaom** [comment]
I think the docstring should be very short and not aim to replace external package documentation. we duplicate documentation and make more work for ourselves. 

There are already traits for the arguments and their types, but not defaults. Is specifying the defaults really necessary? You can just load the code and instantiate to get defaults if you really want. Eg, "PCA()". 

What I think would be useful is a live link to the package documentation from the model's entry in a `models()` listing or `info("some model")`. Can we make the `package_url` trait a live link? This should at least be possible in Jupyter if not from the REPL.

**Comment by ablaom** [comment]
But, yes, our manual could more guidance, here, thanks!

**Comment by tlienart** [comment]
Oh sorry there's a confusion here, I only meant to make the _actual_ docstring **of** `metadata_*` clearer so that when people do

```julia
julia> ?metadata_pkg
```

they get something more informative.

This stems from a question from the author of JLBoost. 

(But yes I agree with the rest of what you said)
