### ISSUE TITLE
Question about auc 

### ISSUE THREAD

**Issue by Roseck16** [alan-turing-institute/MLJBase.jl#143]
Forgive me if I don't understand, for I have searched in the documentation and looked at the code but I'm still failing to make this work:

Shouldn't auc function work with simple input like: 

```
 a = [0.0, 0.0, 1.0, 1.0]
 b = [1.0, 0.0, 0.0, 1.0]
```

Instead I'm getting the following error:

> MethodError: no method matching (::MLJBase.AUC)(::Array{Float64,1}, ::Array{Float64,1})

**Comment by tlienart** [comment]
Hello,

No AUC expects "probabilistic" input (scores) i.e. vector of `UnivariateFinite`. You can construct them out of raw score vectors if that's what you want; have a look at [the test cases](https://github.com/alan-turing-institute/MLJBase.jl/blob/04393ebb1c25eacc35ef1263b8d4358a00c2f845/test/measures/finite.jl#L118-L159) for explicit examples.
