### ISSUE TITLE
Migrate `is_same_except` method to MLJModelInterface

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJBase.jl#178]
Which should then export it

**Comment by tlienart** [comment]
I had a quick look at this, I'm a bit unclear as to  whether this is useful or not. 

* pro: I understand it's related to the type which  is defined in MLJType, so maybe more consistent to have it there
* con: I can't  see someone using this in their  interface
* con: for consistency, the  entire content of `equality.jl` should be moved to MMI and then re-exported

thoughts?

**Comment by ablaom** [comment]
The use is this: in `update` methods one often wants to check if the old model is the same as the new model with the exception of a single parameter (usually the number of iterations). When a model has a large number of hyper parameters this is a pain and error-prone without such a method. The method is used in `MLJ/src/ensembles.jl` and I have suggested its use by the EvoTrees people. 

As for where to put stuff, I think the best plan is to put everything in the one place, which would need to be MLJModelInterface.

Clearer?
