### ISSUE TITLE
Fail to add because of the upper bound for Tables.jl

### ISSUE THREAD

**Issue by ValdarT** [alan-turing-institute/MLJBase.jl#2]
MLJBase restricts the Tables.jl to version "< 0.1.15" but current DataFrames wants at least version "0.1.15". So if one has DataFrames installed then adding MLJBase fails with the following error:
```
(v1.1) pkg> add "https://github.com/alan-turing-institute/MLJBase.jl"
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Updating git-repo `https://github.com/alan-turing-institute/MLJBase.jl`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Tables [bd369af6]:
 Tables [bd369af6] log:
 ├─possible versions are: [0.1.0-0.1.15, 0.1.17] or uninstalled
 ├─restricted to versions 0.0.0-0.1.14 by MLJBase [a7f614a8], leaving only versions 0.1.0-0.1.14
 │ └─MLJBase [a7f614a8] log:
 │   ├─possible versions are: 0.1.0 or uninstalled
 │   └─MLJBase [a7f614a8] is fixed to version 0.1.0
 └─restricted to versions 0.1.17 by an explicit requirement — no versions left
```

**Comment by ablaom** [comment]
Yes, I am aware of this. There is a bug in Tables.jl which is fixed but not in latest release. Have you tried removing DataFrames from you env, installing MLJ as per README.md and then adding DataFrames afterwards?

**Comment by ValdarT** [comment]
Getting it to work was not an issue thanks to projects/environments in Pkg3, just wanted to make sure it's known that it happens.

**Comment by ablaom** [comment]
Cool. Thanks for letting me know.
