### ISSUE TITLE
Use LittleDicts in UnivariateFinite?

### ISSUE THREAD

**Issue by oxinabox** [alan-turing-institute/MLJBase.jl#22]
`Dicts` as a pretty heavy, mutable type.
They can be subsituted for `OrderedCollections.LittleDicts`,
in particular when using the  constructor tht takes a tuple of keys and a tuple of values.

with the following advantages:

 - immutability: don't want results mutated after the fact
 - order preserving: so that keys will stay in the same order as given by levels, so more readable
 - much faster to read for sizes <32 (which is the main things on is thinking about for many classification problems). Only noticeably slower in the 100s or thousands (depends on the key type. Hashmaps get advantage earlier for simpler keys types with simpler hashes).
 - Much faster to create and less allocating. See below.

Demo: a simplified case for binary classification:
```
using OrderedCollections
using BenchmarkTools

function ld_demo(probs)
    map(probs) do p 
        LittleDict((true,false), (1, 1-p))
    end
end

function hm_demo(probs)
    map(probs) do p 
        Dict(true=>p, false=>1-p)
    end
end

results = rand(10_000);
@btime hm_demo($results);
@btime ld_demo($results);
```

### Results:
```
julia> @btime hm_demo($results);
  904.058 μs (40003 allocations: 4.96 MiB)

julia> @btime ld_demo($results);
  15.077 μs (3 allocations: 234.47 KiB)
```

Major downside is:
 - very large class-classification problems (ideally, would have a compiletime way to swap to an `OrderedDict`, or perhaps a `SortedDict`)
 - adds OrderedCollections dependency. However that is already a downstream dependency of MLJ->StatsBase->DataStructures->OrderedCollections. OrderedCollections is the most widely deployed juli package, it is a dependency of Revise.jl

**Comment by ablaom** [comment]
Sounds good to me. 

@oxinabox Interested in opening  a PR, at your leisure?

**Comment by oxinabox** [comment]
Sure, at some point I will do this, unless some else does first.

**Comment by ablaom** [comment]
Will do along with another refactor now WIP.
