### ISSUE TITLE
Spread remainder evenly among folds in train_test_pairs

### ISSUE THREAD

**Issue by CameronBieganek** [alan-turing-institute/MLJBase.jl#232]
The current behavior of `train_test_pairs` is to place all extra indices in the last fold. This is fine for large datasets, but is rather uneven for small data sets:

```julia
julia> cv = CV(nfolds=10);

julia> rows = 1:99;

julia> mlj_tt_pairs = MLJBase.train_test_pairs(cv, rows);

julia> map(length ∘ last, mlj_tt_pairs)
10-element Array{Int64,1}:
  9
  9
  9
  9
  9
  9
  9
  9
  9
 18
```

Instead, the remainder `r = N mod K` could be [distributed evenly](https://stats.stackexchange.com/a/48161/225507) across the `r` first folds. Here are a couple of ways to implement that:

```julia
using Base.Iterators: partition, flatten
using MLJBase


function my_train_test_pairs1(cv::CV, rows)
    N = length(rows)
    K = cv.nfolds

    if cv.shuffle
        rows=shuffle!(cv.rng, collect(rows))
    end

    # (floor(N/K), remainder)
    n, r = divrem(N, K)
    n > 0 || error("Inusufficient data for $K-fold cross-validation.\n"*
                   "Try reducing nfolds. ")

    m = n + 1 # number of observations in first r folds

    itr1 = partition( 1 : m*r , m)
    itr2 = partition( m*r+1 : N , n)
    test_folds = flatten((itr1, itr2))

    map(test_folds) do test_indices
        test_rows = rows[test_indices]

        train_rows = vcat(
            rows[ 1 : first(test_indices)-1 ],
            rows[ last(test_indices)+1 : end ]
        )

        (train_rows, test_rows)
    end
end


function my_train_test_pairs2(cv::CV, rows)
    N = length(rows)
    K = cv.nfolds

    if cv.shuffle
        rows=shuffle!(cv.rng, collect(rows))
    end

    # (floor(N/K), remainder)
    n, r = divrem(N, K)
    n > 0 || error("Inusufficient data for $K-fold cross-validation.\n"*
                   "Try reducing nfolds. ")

    m = n + 1
    M = m * r

    test_folds = map(1:K) do k
        if k <= r
            1 + (k-1)*m : k*m
        else
            j = k - r
            M + 1 + (j-1)*n : M + j*n
        end
    end

    map(test_folds) do test_indices
        test_rows = rows[test_indices]

        train_rows = vcat(
            rows[ 1 : first(test_indices)-1 ],
            rows[ last(test_indices)+1 : end ]
        )

        (train_rows, test_rows)
    end
end
```

Here's the new implementation in action:

```julia
julia> my_tt_pairs = my_train_test_pairs1(cv, rows);

julia> map(length ∘ last, my_tt_pairs)
10-element Array{Int64,1}:
 10
 10
 10
 10
 10
 10
 10
 10
 10
  9
```

I don't think partitioning the data is a bottleneck in ML pipelines, but if performance is a concern, `my_test_train_pairs1` is slightly slower than `my_test_train_pairs2` and `MLJBase.test_train_pairs`. Here are the benchmarks:

```julia
julia> using BenchmarkTools

julia> cv = CV(nfolds=10);

julia> rows = 1:100_009;

julia> @btime MLJBase.train_test_pairs($cv, $rows);
  445.345 μs (117 allocations: 6.87 MiB)

julia> @btime my_train_test_pairs1($cv, $rows);
  655.561 μs (234 allocations: 8.55 MiB)

julia> @btime my_train_test_pairs2($cv, $rows);
  444.728 μs (115 allocations: 6.87 MiB)
```

I think the small underperformance of `my_train_test_pairs1` could be ameliorated if Base had a specialized `Iterators.partition` method for `AbstractRange`. Currently the `eltype` of `partition(::UnitRange, ::Int)` is `Vector{Int}` rather than `UnitRange`. However, I think `my_train_test_pairs1` is conceptually more clear and more readable than `my_train_test_pairs2`.

I can put in a PR for this if there is interest.

**Comment by ablaom** [comment]
@CameronBieganek That's awesome. I vote for clarity over reading. The benchmarks are same order of magnitude and bottlenecks in machine learning are somewhere else 99.9 % of time.

Love a PR! Be great if you could include an updated doc-string that explains exactly what is implemented.

**Comment by ablaom** [comment]
BTW, please make PR onto `dev` instead of `master`. 

[contributing guidelines](https://github.com/alan-turing-institute/MLJ.jl/blob/master/CONTRIBUTING.md)

**Comment by CameronBieganek** [comment]
Ok, sounds good. I should be able to put in a PR sometime this week.

**Comment by CameronBieganek** [comment]
Sorry, I just started working on actually implementing this today. I'm trying to grok the stratified CV unit test [here](https://github.com/alan-turing-institute/MLJBase.jl/blob/9ef1a59e40803ce4a85e77cb523211d609a63d94/test/resampling.jl#L211). I'd like to update that unit test with the new expected behavior before I make my changes, rather than the other way around. :)

I should be able to figure it out, I just need to read the `train_test_pairs(::StratifiedCV, ...)` method, which I've been avoiding doing so far. I'm also going to add a simple test case for `train_test_pairs(::CV, ...)`.

**Comment by tlienart** [comment]
> EDIT:
> Also, is it OK if I add `.vscode` to `.gitignore`?

no problem
