### ISSUE TITLE
`evaluate!` hangs instead of throwing exceptions (flawed exception handling)

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJBase.jl#235]
A couple of times I have run into this problem. There is an Exception being thrown during `evaluate!` but instead of it making the light of day, the method call just hangs, because of the way we're currently using channels/tasks (even in CPU1() mode). 

Here's an example to reproduce the hanging:

```julia
using MLJ

X, y = @load_iris
model = @load ConstantClassifier

bad_loss(yhat, y) = throw(Exception)
evaluate(model, X, y, measure=bad_loss) # hangs!!!
```

Here's relevant code (from src/resampling):

```julia
    p = Progress(nfolds, ... )
    channel = RemoteChannel(()->Channel{Bool}(nfolds) , 1)

    function get_measurements(mach, k)
        < do stuff that might throw Exception >
        ...
        put!(channel, true)
    end

    @sync begin
        # printing the progress bar
        @async while take!(channel)
            verbosity < 1 || next!(p)
        end

        @async global measurements_flat =
            _evaluate!(get_measurements,
                       machines,
                       acceleration,
                       nfolds,
                       channel)
    end
```
where `_evaluate!` is this:

```julia
function _evaluate!(func, machines, ::CPU1, nfolds, channel)
    generator = (begin
                     r = func(machines[1], k)
                     put!(channel, true)
                     r
                 end for k in 1:nfolds)
    ret = reduce(vcat, generator)
    put!(channel, false)
    return ret
end
```
I should like to keep the task mechanism (b/s it is needed in the other acceleration modes) but am not sure how to handle the exceptions properly.

@OkonSamuel  @jpsamaroo

**Comment by OkonSamuel** [comment]
@ablaom the hanging is probably due to the blocking effect of `take!` in 
```julia
    @sync begin
        # printing the progress bar
        @async while take!(channel)
            verbosity < 1 || next!(p)
        end

        @async global measurements_flat =
            _evaluate!(get_measurements,
                       machines,
                       acceleration,
                       nfolds,
                       channel)
    end
```
The code runs well with just one task. There is no need for the other `@async` hence the above code should be.
```julia
    @sync begin
        # printing the progress bar
        @async while take!(channel)
            verbosity < 1 || next!(p)
        end

        global measurements_flat =
            _evaluate!(get_measurements,
                       machines,
                       acceleration,
                       nfolds,
                       channel)
    end
```
this  allows the exception to be properly thrown.
I ran the `MLJBase` tests on my computer with `julia1.4` and it passes.

**Comment by OkonSamuel** [comment]
@ablaom . There is another issue that is worth noting when using these progress meters is that they slow down the code considerably for large computations ( the most likely cause is that the `put!`and `take!` methods are slow). I recommend that these progress bars be optional.

**Comment by OkonSamuel** [comment]
to see this take the following modified example from [ProgressMeter.jl](https://github.com/timholy/ProgressMeter.jl)
```julia
using ProgressMeter
using Distributed
nfolds=100000000
p = Progress(nfolds)
channel = RemoteChannel(()->Channel{Bool}(nfolds), 1)

@sync begin
    # this task prints the progress bar
    @async while take!(channel)
        next!(p)
    end

    # this task does the computation
    @async begin
        @distributed (+) for i in 1:nfolds
            put!(channel, true)
            i^2
        end
        put!(channel, false) # this tells the printing task to finish
    end
end
```
this ran for roughly 195s on my PC
after removing all `put!` and `take!` functions the above code ran for 0.07s

**Comment by OkonSamuel** [comment]
@ablaom. Should i open a PR to fix this

**Comment by ablaom** [comment]
That would be awesome. Progress bars could turn of for verbosity <= 0, unless that is already the case.

**Comment by OkonSamuel** [comment]
@ablaom. Taking a look at my example again i saw i tested on a high number of folds which isn't practicable. Most cases in practice `nfolds <=10`. So i guess it doesn't affect the existing codes performance much.

**Comment by OkonSamuel** [comment]
@ablaom. I believe i can close this now
