### ISSUE TITLE
nrows gives wrong answer for row tables

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJBase.jl#246]
```julia
julia> using MLJBase, Tables

julia> X = Tables.table(rand(2,3));

julia> Xr = Tables.rowtable(X);

julia> nrows(X)  # hooray
2

julia> nrows(Xr) # boo hoo
0
```

**Comment by ablaom** [comment]
Seems to be a Tables.jl issue:

https://github.com/JuliaData/Tables.jl/issues/170

**Comment by ablaom** [comment]
No, turns out `Tables.rowcount` is a private method we should not use. 

I think we can substitute this:

```julia
function nrows(X)
    Tables.istable(X) || throw(ArgumentError)
    Tables.columnaccess(X) || return length(collect(X))
    # if has columnaccess
    cols = Tables.columntable(X)
    !isempty(cols) || return 0
    return length(cols[1])
end
```

I got this from MLJFlux which I must have copied from an earlier version of MLJBase 😵

**Comment by tlienart** [comment]
it's a bit weird that Tables doesn't expose something like it (?)

**Comment by ablaom** [comment]
I guess they are not in the business of iterating over rows, only abstractly exposing such iterators.
