### ISSUE TITLE
Tessellate levels across folds in stratified CV

### ISSUE THREAD

**Issue by CameronBieganek** [alan-turing-institute/MLJBase.jl#248]
While updating `train_test_pairs(::CV, ...)` I noticed an interesting behavior for stratified CV. It doesn't really matter much for large data sets, but for small data sets you can see a small anomaly. With the old `train_test_pairs(::CV, ...)`, if you take `y = categorical(collect('a'^4 * 'b'^4 * 'c'^4))` and use a 3-fold stratified CV, the classes would stack into the folds like this:

```
      c
c  c  c
      b
b  b  b
      a
a  a  a
```

where columns represent folds. With the new `train_test_pairs(::CV, ...)`, now they stack like this:

```
c
c  c  c
b
b  b  b
a
a  a  a
```

Probably the right way to stack them would be like this:

```
c  c  c
b  b  c
a  b  b
a  a  a
```

Here is one possible implementation to achieve the "tessellation" shown above:

```julia
function train_test_pairs4(stratified_cv::StratifiedCV, rows, X, y)

    st = scitype(y)
    st <: AbstractArray{<:Finite} ||
        error("Supplied target has scitpye $st but stratified "*
              "cross-validation applies only to classification problems. ")

    n_folds = stratified_cv.nfolds

    freq_given_level = countmap(y[rows])
    minimum(values(freq_given_level)) >= n_folds ||
        error("The number of observations for which the target takes on a "*
              "given class must, for each class, exceed `nfolds`. Try "*
              "reducing `nfolds`. ")

    if stratified_cv.shuffle
        rows=shuffle!(stratified_cv.rng, collect(rows))
    end

    n_obs = length(rows)
    obs_per_fold, rem = divrem(n_obs, n_folds)

    # The next two steps can be thought of as reshaping sorted_rows into a
    # ragged matrix with n_folds rows. Each row is a fold. There are
    # obs_per_fold+1 columns in the first r rows and obs_per_fold columns in
    # the remaining rows. Because sorted_rows is sorted by the category
    # levels, and because matrices are column-major, the levels are spread
    # evenly between the rows.

    sorted_rows = sort(rows; by=r -> y[r], alg=MergeSort)

    folds = map(1:n_folds) do i
        len = i <= rem ? obs_per_fold+1 : obs_per_fold
        ind = range(i; step=n_folds, length=len)
        sorted_rows[ind]
    end

    map(1:n_folds) do i
        train_folds = vcat(folds[ 1 : i-1 ], folds[ i+1 : end ])
        train = reduce(vcat, train_folds)
        (train, folds[i])
    end
end
```

**Comment by CameronBieganek** [comment]
A few questions came up while I was looking into this.

- Why does the current `train_test_rows(::StratifiedCV, ...)` method have an `X` argument that is unused?

- With the new implementation, I think we can actually get rid of the following chunk of code:

```julia
freq_given_level = countmap(y[rows])
minimum(values(freq_given_level)) >= n_folds ||
    error("The number of observations for which the target takes on a "*
          "given class must, for each class, exceed `nfolds`. Try "*
          "reducing `nfolds`. ")
```

It seems that restriction was there because the previous implementation called `train_test_pairs(::CV, ...)`, which requires having `n_folds >= n_observations`. The only question is whether we still want something like that on a statistical basis. I think it's statistically ok if there's only instance of a particular level in the response variable.

- Do we need the following chunk from the old implementation?

```julia
# restore ordering specified by rows:
trains_per_fold = map(trains_per_fold) do train
    filter(in(train), rows)
end
tests_per_fold = map(tests_per_fold) do test
    filter(in(test), rows)
end
```

Statistically speaking, I don't see why we need to maintain the order given in `rows`. Is there some process somewhere in MLJ that requires the order given in `rows` to be maintained? The problem with the above chunk is that it is O(n^2), so it doesn't scale well. The following performance test is from the `dev` branch:

```julia
N = 30_000
rows = 1:300_000
cv = CV(nfolds=5)
scv = StratifiedCV(nfolds=5)

y = vcat(fill(:a, N), fill(:b, 2N), fill(:c, 3N), fill(:d, 4N)) |>
	shuffle |>
	categorical;
```

```julia
julia> @btime MLJBase.train_test_pairs($cv, $rows);
  578.974 μs (67 allocations: 9.16 MiB)

julia> @time MLJBase.train_test_pairs(scv, rows, nothing, y)
146.627095 seconds (5.25 M allocations: 363.398 MiB, 0.08% gc time)
```

147 seconds seems like a lot just to partition 300,000 rows. Partitioning 3 million rows would take about 4 hours.

**Comment by ablaom** [comment]
@CameronBieganek Thanks indeed for this.

> Why does the current train_test_rows(::StratifiedCV, ...) method have an X argument that is unused?

Keen observation. I think you can indeed drop the `X` because of [this code](https://github.com/alan-turing-institute/MLJBase.jl/blob/9553505dc461645e8798d474705a1e0db812ef41/src/resampling.jl#L14).
The other signatures exist because other resampling strategies might need to see features, for example in stratifying according to one or more categorical features, instead of the target.

> I think it's statistically ok if there's only instance of a particular level in the response variable.

Agreed.

> Statistically speaking, I don't see why we need to maintain the order given in rows. Is there some process somewhere in MLJ that requires the order given in rows to be maintained? 

Not in MLJ. I don't think it needs to stay (or it could be an option controlled by a new hyper parameter, defaulting to no sorting). Preserving order is a feature of the scikit-learn implementation, if I recall correctly. I can't think of a common use-case requiring this - maybe in time-series, but you don't generally use CV there. 

Your implementation looks very clean and I'd support this, assuming you can include a human readable (but necessarily technical) doc-string explaining exactly what the algorithm is doing, or refer to a paper or url where this is already documented.

Many thanks for this. Love to see a PR along these lines.

**Comment by CameronBieganek** [comment]
Oops, I was missing an important word from that sentence. It should have been "I think it's statistically ok if there's only [one] instance of a particular level in the response variable." Do you still agree with that sentence? :)

I just looked at the sklearn docs for StratifiedKFold now. My implementation fails two of their four criterion:

>- Be invariant to class label: relabelling y = ["Happy", "Sad"] to y = [1, 0] should not change the indices generated.
>- Preserve order dependencies in the dataset ordering, when shuffle=False: all samples from class k in some test set were contiguous in y, or separated in y by samples from classes other than k.

My implementation is not invariant to class relabeling, since the first step is to sort the rows lexicographically by class label. I think I have an idea for a different algorithm that might satisfy both criterion. I'll also take a look at the sklearn implementation to see what they do.

**Comment by CameronBieganek** [comment]
I've thought a bit more about the row ordering. Vanilla cross-validation assumes that the data is i.i.d. I think that stratified cross-validation should also assume i.i.d. data. Thus, `CV` and `StratifiedCV` should not guarantee that row order is preserved (though in practice they might preserve row order when `shuffle=False`). If you believe your data is not i.i.d. (e.g., the rows are auto-correlated), then you should use a `TimeSeriesCV`, `GroupCV`, or `StratifiedGroupCV`, (which haven't been implemented yet), or a custom `ResamplingStrategy`.

**Comment by ablaom** [comment]
> I've thought a bit more about the row ordering. Vanilla cross-validation assumes that the data is i.i.d. I think that stratified cross-validation should also assume i.i.d. data. Thus, CV and StratifiedCV should not guarantee that row order is preserved

Yes, I think that it fair to assume that CV and StratifiedCV are only applied in the i.i.id setting and so we need not require row-order preservation. 

> TimeSeriesCV, GroupCV, or StratifiedGroupCV, (which haven't been implemented yet)

Are you volunteering? 😄 

BTW  Your CV PR (which was merged onto dev but then reverted) now lives [here](https://github.com/alan-turing-institute/MLJBase.jl/pull/243). I'm holding off for the next minor release.

**Comment by CameronBieganek** [comment]
> Are you volunteering? 😄

There's a good chance I'll volunteer for those, but I'll let you know definitively closer to when I start. :)

**Comment by CameronBieganek** [comment]
I should be able to work on this sometime between now and Sunday. Sorry for the delay!

**Comment by ablaom** [comment]
@CameronBieganek FYI, your earlier PR is now live on MLJBase 0.13.0 (but not at MLJ yet)

**Comment by CameronBieganek** [comment]
# Intro

I've come up with two different stratified CV algorithms. The first one, shown above in the original post, is O(n log n) since is has a sort in it. I also came up with an O(n) algorithm, though in practice the performance of the two is pretty similar. Additionally, for each algorithm I have two variants: one that is invariant to label renaming and one that is not.

Question: Do we really care about invariance to label renaming? The algorithms that are not invariant to label renaming will still produce correct stratified CVs, they'll just happen to return a different choice of row indices for each fold than they did before the renaming. Adding invariance to the algorithms makes the code a little more complicated, but oddly enough the invariant versions appear to be slightly more performant.

# Code for the four variants

### Sort based algorithm (not invariant)

```julia
function train_test_pairs_sort_not_invariant(stratified_cv::StratifiedCV, rows, y)

    st = scitype(y)
    st <: AbstractArray{<:Finite} ||
        error("Supplied target has scitpye $st but stratified "*
              "cross-validation applies only to classification problems. ")

    if stratified_cv.shuffle
        rows=shuffle!(stratified_cv.rng, collect(rows))
    end

    n_obs = length(rows)
    n_folds = stratified_cv.nfolds
    obs_per_fold, rem = divrem(n_obs, n_folds)

    # The next two steps can be thought of as reshaping sorted_rows into a
    # ragged matrix with n_folds rows. Each row is a fold. There are
    # obs_per_fold+1 columns in the first r rows and obs_per_fold columns in
    # the remaining rows. Because sorted_rows is sorted by the category
    # levels, and because matrices are column-major, the levels are spread
    # evenly between the rows.

    sorted_rows = sort(rows; by=(i -> y[i]), alg=MergeSort)

    folds = map(1:n_folds) do i
        len = i <= rem ? obs_per_fold+1 : obs_per_fold
        ind = range(i; step=n_folds, length=len)
        sorted_rows[ind]
    end

    map(1:n_folds) do i
        train_folds = vcat(folds[ 1 : i-1 ], folds[ i+1 : end ])
        train = reduce(vcat, train_folds)
        (train, folds[i])
    end
end
```

### Sort based algorithm (invariant)

```julia
function train_test_pairs_sort_invariant(stratified_cv::StratifiedCV, rows, y)

    st = scitype(y)
    st <: AbstractArray{<:Finite} ||
        error("Supplied target has scitpye $st but stratified "*
              "cross-validation applies only to classification problems. ")

    if stratified_cv.shuffle
        rows=shuffle!(stratified_cv.rng, collect(rows))
    end

    n_obs = length(rows)
    n_folds = stratified_cv.nfolds
    obs_per_fold, rem = divrem(n_obs, n_folds)

    # The next two steps can be thought of as reshaping sorted_rows into a
    # ragged matrix with n_folds rows. Each row is a fold. There are
    # obs_per_fold+1 columns in the first r rows and obs_per_fold columns in
    # the remaining rows. Because sorted_rows is sorted by the category
    # levels, and because matrices are column-major, the levels are spread
    # evenly between the rows.

    # unique() preserves the order of appearance of the levels.
    # We need this so that the results are invariant to renaming of the levels.
    y_included = y[rows]
    levels = unique(y_included)

    sort_key = indexin(y_included, levels)

    # Collecting the zip below is much slower and performs many more
    # allocations if we leave the sort_key element type as Union{Nothing, Int}.
    sort_key_pure = convert(Vector{Int}, sort_key)
    rows_sort_key = collect(zip(rows, sort_key_pure))

    sorted_row_tuples = sort(rows_sort_key; by=last, alg=MergeSort)
    sorted_rows = first.(sorted_row_tuples)

    folds = map(1:n_folds) do i
        len = i <= rem ? obs_per_fold+1 : obs_per_fold
        ind = range(i; step=n_folds, length=len)
        sorted_rows[ind]
    end

    map(1:n_folds) do i
        train_folds = vcat(folds[ 1 : i-1 ], folds[ i+1 : end ])
        train = reduce(vcat, train_folds)
        (train, folds[i])
    end
end
```

### O(n) algorithm (not invariant)

```julia
function train_test_pairs_O_n_not_invariant(stratified_cv::StratifiedCV, rows, y)

    st = scitype(y)
    st <: AbstractArray{<:Finite} ||
        error("Supplied target has scitpye $st but stratified "*
              "cross-validation applies only to classification problems. ")

    if stratified_cv.shuffle
        rows=shuffle!(stratified_cv.rng, collect(rows))
    end

    n_folds = stratified_cv.nfolds
    n_obs = length(rows)
    obs_per_fold = div(n_obs, n_folds)

    y_included = y[rows]
    level_count_dict = countmap(y_included)
    y_levels = keys(level_count_dict)
    level_count = collect(values(level_count_dict))

    # Use this vector to determine in which fold to put the i-th observation.
    fold_lookup = collect(Itr.take(Itr.cycle(1:n_folds), n_obs))

    # For each level, the index of fold_lookup where you start looking.
    initial_lookup_indices = 1 .+ cumsum([0; level_count[1:end-1]])

    lookup_indices = Dict(y_levels .=> initial_lookup_indices)

    folds = [Int[] for _ in 1:n_folds]
    for fold in folds
        sizehint!(fold, obs_per_fold)
    end

    for i in 1:n_obs
        level = y_included[i]

        lookup_index = lookup_indices[level]
        lookup_indices[level] = lookup_index + 1

        fold_index = fold_lookup[lookup_index]
        push!(folds[fold_index], rows[i])
    end

    map(1:n_folds) do i
        train_folds = vcat(folds[ 1 : i-1 ], folds[ i+1 : end ])
        train = reduce(vcat, train_folds)
        (train, folds[i])
    end
end
```

### O(n) algorithm (invariant)

```julia
function train_test_pairs_O_n_invariant(stratified_cv::StratifiedCV, rows, y)

    st = scitype(y)
    st <: AbstractArray{<:Finite} ||
        error("Supplied target has scitpye $st but stratified "*
              "cross-validation applies only to classification problems. ")

    if stratified_cv.shuffle
        rows=shuffle!(stratified_cv.rng, collect(rows))
    end

    n_folds = stratified_cv.nfolds
    n_obs = length(rows)
    obs_per_fold = div(n_obs, n_folds)

    y_included = y[rows]
    level_count = countmap(y_included)

    # unique() preserves the order of appearance of the levels.
    # We need this so that the results are invariant to renaming of the levels.
    y_levels = unique(y_included)
    ordered_level_count = [level_count[level] for level in y_levels]

    # Use this vector to determine in which fold to put the i-th observation.
    fold_lookup = collect(Itr.take(Itr.cycle(1:n_folds), n_obs))

    # For each level, the index of fold_lookup where you start looking.
    initial_lookup_indices = 1 .+ cumsum([0; ordered_level_count[1:end-1]])

    lookup_indices = Dict(y_levels .=> initial_lookup_indices)

    folds = [Int[] for _ in 1:n_folds]
    for fold in folds
        sizehint!(fold, obs_per_fold)
    end

    for i in 1:n_obs
        level = y_included[i]

        lookup_index = lookup_indices[level]
        lookup_indices[level] = lookup_index + 1

        fold_index = fold_lookup[lookup_index]
        push!(folds[fold_index], rows[i])
    end

    map(1:n_folds) do i
        train_folds = vcat(folds[ 1 : i-1 ], folds[ i+1 : end ])
        train = reduce(vcat, train_folds)
        (train, folds[i])
    end
end
```

# Output

Here's a simple test case:

```julia
y = categorical(
    ['b', 'c', 'a', 'b', 'b', 'b', 'c', 'c', 'c', 'a', 'a', 'a']
)
scv = StratifiedCV(nfolds=3)
```

And here's the output for each variant. You can see that the existing `train_test_pairs` puts the extra observation for each level in the first fold:

```julia
julia> MLJBase.train_test_pairs(scv, 1:12, y)
3-element Array{Tuple{Array{Int64,1},Array{Int64,1}},1}:
 ([5, 6, 8, 9, 11, 12], [1, 4, 2, 7, 3, 10])
 ([1, 4, 6, 2, 7, 9, 3, 10, 12], [5, 8, 11])
 ([1, 4, 5, 2, 7, 8, 3, 10, 11], [6, 9, 12])

julia> MLJBase.train_test_pairs_sort_not_invariant(scv, 1:12, y)
3-element Array{Tuple{Array{Int64,1},Array{Int64,1}},1}:
 ([10, 1, 6, 8, 11, 4, 2, 9], [3, 12, 5, 7])
 ([3, 12, 5, 7, 11, 4, 2, 9], [10, 1, 6, 8])
 ([3, 12, 5, 7, 10, 1, 6, 8], [11, 4, 2, 9])

julia> MLJBase.train_test_pairs_sort_invariant(scv, 1:12, y)
3-element Array{Tuple{Array{Int64,1},Array{Int64,1}},1}:
 ([4, 2, 9, 11, 5, 7, 3, 12], [1, 6, 8, 10])
 ([1, 6, 8, 10, 5, 7, 3, 12], [4, 2, 9, 11])
 ([1, 6, 8, 10, 4, 2, 9, 11], [5, 7, 3, 12])

julia> MLJBase.train_test_pairs_O_n_not_invariant(scv, 1:12, y)
3-element Array{Tuple{Array{Int64,1},Array{Int64,1}},1}:
 ([3, 5, 7, 12, 1, 6, 8, 10], [2, 4, 9, 11])
 ([2, 4, 9, 11, 1, 6, 8, 10], [3, 5, 7, 12])
 ([2, 4, 9, 11, 3, 5, 7, 12], [1, 6, 8, 10])

julia> MLJBase.train_test_pairs_O_n_invariant(scv, 1:12, y)
3-element Array{Tuple{Array{Int64,1},Array{Int64,1}},1}:
 ([2, 4, 9, 11, 3, 5, 7, 12], [1, 6, 8, 10])
 ([1, 6, 8, 10, 3, 5, 7, 12], [2, 4, 9, 11])
 ([1, 6, 8, 10, 2, 4, 9, 11], [3, 5, 7, 12])
```

# Benchmarking

For the benchmarking, I removed a couple chunks from the existing `train_test_pairs` in order to have an apples to apples comparison. For very large numbers of rows, you can start to see the difference between the existing algorithm, the sort based algorithm, and the O(n) algorithm.

```julia
using BenchmarkTools

scv = StratifiedCV(nfolds=5)

N = 10_000_000
rows = 1:(10N)

y = (
    vcat(fill(:a, N), fill(:b, 2N), fill(:c, 3N), fill(:d, 4N))
    |> shuffle
    |> categorical
);
```

```julia
julia> @btime MLJBase.train_test_pairs($scv, $rows, $y);
  18.414 s (1259 allocations: 21.88 GiB)

julia> @btime MLJBase.train_test_pairs_sort_not_invariant($scv, $rows, $y);
  15.566 s (63 allocations: 4.84 GiB)

julia> @btime MLJBase.train_test_pairs_sort_invariant($scv, $rows, $y);
  14.283 s (98 allocations: 10.15 GiB)

julia> @btime MLJBase.train_test_pairs_O_n_not_invariant($scv, $rows, $y);
  10.204 s (109 allocations: 4.84 GiB)

julia> @btime MLJBase.train_test_pairs_O_n_invariant($scv, $rows, $y);
  8.918 s (117 allocations: 4.84 GiB)
```

**Comment by ablaom** [comment]
Thank you indeed for this comprehensive contribution and assessment. 

All new implemenations have an order of magnitude fewer allocations that the existing one, which is great! I would be happy for you to make an executive decision about what goes in the PR.  The performance difference is so small, we may as well preserve the relabelling invariance. Alternatively, add `invariant_to_relabelling` as hyper-parameters and let the user decide.

I'm a little confused on one point. When you say "sort-based", does this mean the order of elements in a fold respects the original order in `rows`? Or rather just that the algorithm uses sort to come up with some valid stratified set of folds?

**Comment by ablaom** [comment]
Oh, by the way, I have created a new branch called `breaking`. Please make any breaking PR there. I'm trying to stack up more of these breaking changes before tagging next minor release.

**Comment by CameronBieganek** [comment]
> I would be happy for you to make an executive decision about what goes in the PR.

Sounds good. I'll make a PR soon.

> I'm a little confused on one point. When you say "sort-based", does this mean the order of elements in a fold respects the original order in `rows`? Or rather just that the algorithm uses sort to come up with some valid stratified set of folds?

The second of those two. The algorithm uses `sort` and hence has O(n log n) time comlexity, but the order of the elements in a fold does not respect the original order in `rows`. Sorry for the confusion.
