### ISSUE TITLE
Revisiting report and fitted_params for composite models

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJBase.jl#254]
Currently `fitted_params` returns a named tuple `(machines=..., fitted_params=...)` for any composite model. If `FP = fitted_params(model, fitresult)` then `FP.fitted_params[i]` is the fitted params for `FP.machines[i]` for each `i`. 

The `report` method for composites follows the same pattern. 

This has been confusing to users in at least two cases, lately [here](https://github.com/alan-turing-institute/MLJ.jl/issues/492). Perhaps it would be better to return `(fitted_params_given_machine=d)` where `d` is a dictionary of fitted parameters keyed on the machines. Or just return `d`. 

Thoughts anyone?

**Comment by OkonSamuel** [comment]
@ablaom. I prefer the dictionary representation.

**Comment by ablaom** [comment]
Okay, sounds like a plan. I will keep the `machines` key to save user doing `machines = collect(keys(FP.fitted_params_given_machine))` to get the keys of the dictionary, which are otherwise not accessible.

**Comment by ablaom** [comment]
I could also add `fitted_params` key, but think this will just lead to original confusion.

**Comment by ablaom** [comment]
Here's the proposed doc-string for fitted_params:

--- 

    fitted_params(mach)

Return the learned parameters for a machine `mach` that has been
`fit!`, for example the coefficients in a linear model.

This is a named tuple and human readable if possible.

If `mach` is a machine for a composite model, then the returned value
has keys `machines` and `fitted_params_given_machine`, whose
corresponding values are a vector of (nodal) machines appearing in the
underlying learning network, and a dictionary of reports keyed on
those machines.

```julia
using MLJ
X, y = @load_crabs;
pipe = @pipeline MyPipe(
    std = Standardizer(),
    clf = @load LinearBinaryClassifier pkg=GLM
)
mach = machine(MyPipe(), X, y) |> fit!
fp = fitted_params(mach)
2-element Array{Any,1}:
 NodalMachine{LinearBinaryClassifier{LogitLink}} @ 1…57
 NodalMachine{Standardizer} @ 7…33

machs = fp.machines
fp.fitted_params_given_machine[machs[1]]
(coef = [121.05433477939319, 1.5863921128182814,
         61.0770377473622, -233.42699281787324, 72.74253591435117],
 intercept = 10.384459260848505,)
