### ISSUE TITLE
Model interface defined?

### ISSUE THREAD

**Issue by juliohm** [alan-turing-institute/MLJBase.jl#26]
By quickly reading the source code, I couldn't find a ML model interface like the one defined in ScikitLearnBase.jl. Could you please explain the interface implemented in MLJBase.jl? Is there an interface already?

**Comment by ablaom** [comment]
There is a detailed description of the model interface in the MLJ [docs](https://alan-turing-institute.github.io/MLJ.jl/dev/adding_models_for_general_use/). Happy to provide overview. The most effective start would be a face-to-face call. See my slack message.

**Comment by juliohm** [comment]
Thank you @ablaom , couldn't find your slack message though. I will read the docs to see what is already there.
