### ISSUE TITLE
partition(... stratify=y) not working if y is categorical

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJBase.jl#274]
The following is taken from the tests with the numerical `y` replaced with a categorical one:

```julia
y = ones(Int, 1000)
y[end-100:end] .= 0;            # 90%
y = categorical(y)
train, test = partition(eachindex(y), 0.8, stratify=y, rng=34)

┌ Warning: Some splits have a single or no representative of some class.
└ @ MLJBase ~/Dropbox/Julia7/MLJ/MLJBase/src/data/data.jl:53
┌ Warning: Some splits have a single or no representative of some class.
└ @ MLJBase ~/Dropbox/Julia7/MLJ/MLJBase/src/data/data.jl:68
(Int64[], Int64[])
```

Empty tuples returned!

Sometimes `y` will be `Count`, as in this example, but typically `y` will categorical (`elscitype(y) <: Finite`), yes?

**Comment by ablaom** [comment]
@tlienart 
@CameronBieganek

**Comment by tlienart** [comment]
What's the question here? Yeah it looks pretty broken.

If you add `int(y)` in the partition it works so I guess it doesn't get the levels properly
