### ISSUE TITLE
Help people quickly build UnivariateFinite object

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJBase.jl#282]
It seems that people are often getting tripped up by `UnivariateFinite` object. Typical situation:

- User has some way of getting a vector of **scores** `s` 
- User assumes that given it's just a single vector of scores it's obvious it's a binary case
- User gets annoyed because they can't just use `auc` or some similar measures.
- User asks and we end up saying something like:

```julia
c = classes(categorical([:label0, :label1])[1])
y = [UnivariateFinite(c, [1-s[i], s[i]]) for i in s]
``` 

what would be good is to just have a simple way to do this directly something like

```
UnivariateFinite(s) # ==> does the above
UnivariateFinite(s, [:label_0, :label_1]) # ==> does the above with specific labels
UnivariateFinite(w) # ==> with w has c columns, do it with c labels
UnivariateFinite(w,  [:label_0, :label_1, :label_2]) # ==> same but specifying labels
```

Solving this would go along with solving https://github.com/alan-turing-institute/MLJ.jl/issues/511

**Comment by ablaom** [comment]
I think this is a great idea. While not abolutely necessary, it would be less work overall to incorporate with [this](https://github.com/alan-turing-institute/MLJ.jl/issues/511) remedy to another issue.
