### ISSUE TITLE
make_regression creating X with constant column

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJBase.jl#291]
**edited**

```julia
using MLJBase
import Random.seed!
seed!(123)
X, y = make_regression()
julia> std(X.x3)
0.0
```

**Comment by ablaom** [comment]
@davidbp @tlienart Or is this intentional?

**Comment by tlienart** [comment]
Intentional, just do `intercept=false` if you don’t want that column.

**Comment by tlienart** [comment]
On second thoughts it probably make sense to drop the column at the end
