### ISSUE TITLE
Measures of forecast accuracy

### ISSUE THREAD

**Issue by azev77** [alan-turing-institute/MLJBase.jl#294]
Rob's paper: https://robjhyndman.com/papers/mase.pdf (might be a newer version)
has a nice review of different measures of forecast accuracy.

Would be nice to incorporate at some point. 
(They focus on univariate time series, but their results apply more broadly.)

2.1  Scale-dependent measures
Mean Square Error (MSE)
Root Mean Square Error (RMSE)
Mean Absolute Error (MAE)
Median Absolute Error (MdAE)

2.2  Measures based on percentage errors
Mean Absolute Percentage Error (MAPE)
Median Absolute Percentage Error (MdAPE)
Root Mean Square Percentage Error (RMSPE)
Root Median Square Percentage Error (RMdSPE)
Symmetric Mean Absolute Percentage Error (sMAPE)
Symmetric Median Absolute Percentage Error (sMdAPE)

2.3  Measures based on relative errors (Relative to a benchmark)
Mean Relative Absolute Error (MRAE)
Median Relative Absolute Error (MdRAE)
Geometric Mean Relative Absolute Error (GMRAE)

2.4  Relative measures. {is Rsquared in this category?}
RelMAE=MAE/MAEb

3  Scaled errors
Mean Absolute Scaled Error (MASE)

Check out his TS book too: https://otexts.com/fpp2/accuracy.html

**Comment by ablaom** [comment]
Sounds good to me. As these are all deterministic measures, it's relatively straightforward to add these.
