### ISSUE TITLE
Can't use MLJ's acceleration resorces on Sklearn models

### ISSUE THREAD

**Issue by OkonSamuel** [alan-turing-institute/MLJBase.jl#297]
Users need to be aware that tuning and evaluation of sklearn(through ScikitLearn.jl) models can't be accelerated in julia see https://github.com/JuliaLang/julia/issues/33893. But using the `n_jobs` parameter in sklearn seems to work.

**Comment by ablaom** [comment]
Thanks for flagging this. 

Does this mean `CPUProcesses()` also fails for python models?

**Comment by OkonSamuel** [comment]
@ablaom, `CPUProcesses` still work. Its just any combination containing `CPUThreads` that would fail.

**Comment by ablaom** [comment]
Closing in favour of https://github.com/alan-turing-institute/MLJ.jl/issues/525
