### ISSUE TITLE
Type piracy of getproperty/setproperty!

### ISSUE THREAD

**Issue by jpsamaroo** [alan-turing-institute/MLJBase.jl#30]
In `src/parameters.jl`, `getproperty` and `setproperty!` are overloaded inappropriately to achieve recursive getting/setting of nested properties. These methods should either be renamed to not overload `Base` methods, or should have one of the arguments (probably the field, `ex`) be constrained to a type declared by MLJBase. A simple wrapper struct around the passed `Expr` would be sufficient to eliminate the type piracy.

**Comment by ablaom** [comment]
Thanks for that. 

If this is type piracy, it is pretty mild and it is extemely natural and  convenient to introduce here. I would hate to force the user to wrap his expressions in our use-case. 

I have invited further comment on discourse:

https://discourse.julialang.org/t/nested-getproperty-requests/27968

**Comment by ablaom** [comment]
On reflection, I'll just make new methods `recursive_getproperty` and `recursive_setproperty!` and use those. To avoid excessive revisioning, I'll put them into MLJ/utilities (they aren't really needed in MLBase) and we can dump the offending MLJBase code for the next patch release.
