### ISSUE TITLE
replace dict of machine

### ISSUE THREAD

**Issue by OkonSamuel** [alan-turing-institute/MLJBase.jl#300]
Just got to know that Julia collections are not thread safe when at least one thread is manipulating the collection. 
This example from discourse for `Dict` explains what i mean
```julia
dict = Dict{Int64,Vector{Float64}}()
nentries = 5e5

Threads.@threads for n in 1:nentries
    dict[n] = [rand() for i in 1:100]
end

@assert length(dict) == nentries
```
The assertion fails.

Currently MLJBase creates a `Dict` of `machines` clones  with a machine for each thread. There is another way to do this without which is thread safe. I'll open a PR soon to fix this.

**Comment by ablaom** [comment]
I think there is dictionary in MLJTuning too.

https://github.com/alan-turing-institute/MLJTuning.jl/blob/f01d231b1a64b7e19d37adffa590c417f9a06268/src/tuned_models.jl#L520
