### ISSUE TITLE
ROC AUC values not returning the correct values when compared to sklearn

### ISSUE THREAD

**Issue by HarrisonWilde** [alan-turing-institute/MLJBase.jl#311]
Hi, please see this MWE below:

```{julia}
y = [1, -1, 1, 1]
ps = [0.4, 0.3, 0.6, 0.7]
c = classes(categorical(y)[1])
yc = categorical(y)
levels!(yc, levels(c))
a = auc([UnivariateFinite(c, [1.0 - p, p]) for p in ps], yc)

julia> a
1.0
```

vs Python's sklearn `roc_auc_score`

```{python}
from sklearn.metrics import roc_auc_score

> roc_auc_score([[1, -1, 1, 1], [-1, 1, -1, -1]], [[0.4, 0.3, 0.6, 0.7], [0.6, 0.7, 0.4, 0.3]])
0.75
```

Would appreciate any help with this.

**Comment by tlienart** [comment]
Hey Harrison, would you mind trying that same example with a couple of vectors of size ~10 and a couple of vectors of size ~50 and report your findings? I think it's just an artifact of the way the score is computed but I could be wrong. That will help me narrow down where the issue is if any

thanks

**Comment by tlienart** [comment]
Ok so here's what I was hoping for:

```julia
using MLJBase
using PyCall
using StableRNGs

rng = StableRNG(01025)

diffs = []

for i in 1:10
    for n in (10, 50, 100, 1000)
        y = ifelse.((rand(rng, n) .< 0.5), -1, 1)
        s = rand(n)

        skm = pyimport("sklearn.metrics")
        sk = skm.roc_auc_score(y, s)

        yc = categorical(y)
        c = classes(yc[1])
        ufv = [UnivariateFinite(c, [1-si, si]) for si in s]

        mlj = auc(ufv, yc)

        push!(diffs, abs(sk - mlj))
    end
end

@show maximum(diffs)
```

Running the above gives me `1.11e-16`, I think that's close enough. 

I'll do  a few more extreme tests pushing the probs but basically the issue here just seems to be an artifact of the toy example.

**Comment by tlienart** [comment]
oh a fun thing to do is to change a few lines to

```julia
push!(sktimes, @elapsed (sk = skm.roc_auc_score(y, s)))
...
push!(mljtimes, @elapsed (mlj = auc(ufv, yc)))
...
```

Then if you do `mean(sktimes ./ mljtimes)` you get a satisfying `32` ...

**Comment by HarrisonWilde** [comment]
Awesome thank you for this Thibaut, that makes it a lot clearer where my thinking was incorrect on this. I think I was unlucky in making multiple toy example that all ended up quite far out but when I automate a wider search of somewhat trivial example I agree with what you have here

**Comment by CameronBieganek** [comment]
@HarrisonWilde 

For your MWE, the scores perfectly separate the two classes, so the correct AUC is 1. The problem with your example is in how you called the scikit-learn function. The correct way to call it for binary classification data is this:

```python
In [1]: from sklearn.metrics import roc_auc_score

In [2]: roc_auc_score([1, -1, 1, 1], [0.4, 0.3, 0.6, 0.7])
Out[2]: 1.0
```

cc: @tlienart
