### ISSUE TITLE
up compat for ProgressMeter to "^1.3"

### ISSUE THREAD

**Issue by OkonSamuel** [alan-turing-institute/MLJBase.jl#324]

**Comment by ablaom** [comment]
@OkonSamuel According to semver version 1.3 is already permitted by the current "^1.1" because the leading digit is no longer 0. You can check locally that you get 1.3 if you update your manifest.

**Comment by ablaom** [comment]
Did you want this as a lower limit?

**Comment by OkonSamuel** [comment]
> @OkonSamuel According to semver version 1.3 is already permitted by the current "^1.1" because the leading digit is no longer 0. You can check locally that you get 1.3 if you update your manifest.

yeah that's true

**Comment by OkonSamuel** [comment]
> Did you want this as a lower limit?

Yea. It appear it has some updates when printing progress bars in jupyter enviroment
