### ISSUE TITLE
Dump DataFrames from test dependencies

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJBase.jl#329]
We shouldn't really need this, and this has a lot of dependencies likely to upset CI at some point (again).

I think that it is enough to check things work using the julia native implementations of Table.jl

**Comment by OkonSamuel** [comment]
@ablaom some important tests currently depend on this dependency

**Comment by ablaom** [comment]
Yes. There is a "using DataFrames" in `/test/data/data.jl` which is not used, as far as I can tell. And there is one in `/test/interface/interface.jl/` which includes `/test/interface/data_utils.jl`, which indeed  has some tests of our data utilities for DataFrames. 

In data_utils.jl we already test the relevant methods on "row tables" and "column tables" and on `TypedTables.Table`s.   In theory, if they work in those cases, shouldn't they work for any implementation of the Tables.jl interface? The methods being tested only depend on Tables.jl methods and nothing specific to the API of those tables. So I am suggesting we comment out the DataFrames tests, and if there are any methods *only* tested on DataFrames, then we refactor those. 

TypedTables could stay as it is very light-weight.
