### ISSUE TITLE
Generalize `partition` to split any table or matrix or vector, not just vector of integers

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJBase.jl#361]
So one could do, for example

```julia
Xtrain, Xtest = partition(X, 0.7)
ytrain, ytest = partition(y, 0.7)
```

if so inclined.

A quick look at the code suggest this wouldn't be too hard to fix. 

cc: @mlonig

**Comment by ablaom** [comment]
@giordano Perhaps you would be interested in this? Requires familiarity with the Tables API and/or the `selectcols` methods defined in MLJBase.

**Comment by giordano** [comment]
Is the output always supposed to be a tuple of vectors?  This is for example what [`Base.Iterators.partition`](https://docs.julialang.org/en/v1/base/iterators/#Base.Iterators.partition) does.  In that case, can't you just flatten the array if not a vector, without changing anything else?

Something like this
```julia
julia> MLJBase.partition(m::AbstractMatrix{Int}, fractions::Real...; kwargs...) = MLJBase.partition(@view(m[:]), fractions...; kwargs...)

julia> m = collect(reshape(1:10, 5, 2))
5×2 Matrix{Int64}:
 1   6
 2   7
 3   8
 4   9
 5  10

julia> MLJBase.partition(m, 0.2, 0.4)
([1, 2], [3, 4, 5, 6], [7, 8, 9, 10])
```

**Comment by ablaom** [comment]
@giordano Thanks for looking into this.

Sorry for not being clearer. The idea is that a vector is split into a tuple of vectors (current behaviour), a matrix should split into a tuple of matrices with the same number of columns (individual rows totally to number of input rows) and similar for tables. So, for example, the desired output of your last call above should be 

```julia
(
[1 6],

[2 7;
 3 8],

[4 9;
 5 10]
)
```

To select rows of any vector, matrix or table `X`, you can use `MLJBase.selectrows(X, I)`.
You can get the number or rows in any vector, matrix or table `X` with `MLJBase.nrows(X)`. 

Unless I'm missing something, I don't think this should be hard. Just use partition on `1:nrows(X)` and then apply `selectrows(X, I)` for `I` in the return value...
