### ISSUE TITLE
Problems with type in range constructor (again)

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJBase.jl#372]
```julia
pca = @load PCA
julia> r = range(pca, :maxoutdim, lower = 1, upper=25)
ERROR: ArgumentError: You must specify values=... for a nominal parameter.
Stacktrace:
 [1] nominal_range(::Type{T} where T, ::Symbol, ::Nothing) at /Users/anthony/.julia/packages/MLJBase/r3heT/src/hyperparam/one_dimensional_ranges.jl:162
 [2] #range#278 at /Users/anthony/.julia/packages/MLJBase/r3heT/src/hyperparam/one_dimensional_ranges.jl:96 [inlined]
 [3] top-level scope at REPL[63]:1
```

The problem is that the default value of  `maxoutdim` is  `nothing`, which MLJ thinks is nominal. The workaround to explicitly specify the type, rather than fetching from the instance provided:

```julia
 r = range(Int, :maxoutdim, lower = 1, upper=25)
```

For now, I will add a more informative error message, but maybe someone can suggest better solution.

**Comment by ablaom** [comment]
So the new error, implemented at https://github.com/alan-turing-institute/MLJBase.jl/pull/371/commits/4b1a178dcfe8a659f03bd8f4e53472a9410c6928, is:

```
julia> range(pca, :maxoutdim, lower = 1, upper=25)
ERROR: ArgumentError: The inferred hyper-parameter type is Nothing, which is nominal. If this is true, you must specify values=... If this is false, specify the correct type as first argument of `range`, as in the example `range(Int, :dummy, lower=1, upper=10)`. 
Stacktrace:
 [1] nominal_range(::Type{T} where T, ::Symbol, ::Nothing) at /Users/anthony/Dropbox/Julia7/MLJ/MLJBase/src/hyperparam/one_dimensional_ranges.jl:162
 [2] #range#278 at /Users/anthony/Dropbox/Julia7/MLJ/MLJBase/src/hyperparam/one_dimensional_ranges.jl:96 [inlined]
 [3] top-level scope at REPL[5]:1
```

**Comment by OkonSamuel** [comment]
The ultimate solution (as implemented in https://github.com/alan-turing-institute/MLJModels.jl/pull/280) would be to discourage using `Union{Nothing, <:Real}` types as field types in model structs.

**Comment by ablaom** [comment]
Yeah.

**Comment by CameronBieganek** [comment]
I might be missing something here, but it seems like a slight change to the API and a change to the implementation of `range` would work better and continue to allow parameter fields to have `Union{Nothing, <:Real}`.

The slight change to the API is that the line in the docs that shows that the signature

```julia
r = range(model, :hyper; values=nothing)
```

is used to create a `NominalRange` can be changed to this:

```julia
r = range(model, :hyper; values)
```

In other words, `range` will create a `NominalRange` if and only if `values` is not `nothing`. Then the implementation of `range` could be something like this:

```julia
function Base.range(model::Union{Model, Type}, field::Union{Symbol,Expr};
                    values=nothing, lower=nothing, upper=nothing,
                    origin=nothing, unit=nothing, scale::D=nothing) where D
    if model isa Model
        value = recursive_getproperty(model, field)
        T = typeof(value)
    else
        T = model
    end
    if !isnothing(values)
        return nominal_range(T, field, values)
    elseif T <: Real
        return numeric_range(T, D, field, lower, upper, origin, unit, scale)
    else
        error("The provided field does not accept real number values and you" *
              "have not provided nominal values via the `values` argument.")
    end
end
```

**Comment by OkonSamuel** [comment]
I guess that should fix this.

**Comment by OkonSamuel** [comment]
Thanks @CameronBieganek your code gave me a way to give a better error msg.
```julia
function Base.range(model::Union{Model, Type}, field::Union{Symbol,Expr};
                    values=nothing, lower=nothing, upper=nothing,
                    origin=nothing, unit=nothing, scale::D=nothing) where D
    if model isa Model
        value = recursive_getproperty(model, field)
        T = typeof(value)
    else
        T = model
    end
    T === Nothing && throw(ArgumentError(
		"The inferred hyper-parameter type is $T and MLJ can't. "*
		"figure out the type of range to be created from the inferred type $T"*
		"Please, specify the correct type as "*
		"first argument of `range`, as in "*
		"the example, "*
		"`range(Int, :dummy, lower=1, upper=10)`. "  ))
    if T <: Real && values === nothing
        return numeric_range(T, D, field, lower, upper, origin, unit, scale)
    else
        return nominal_range(T, field, values)
    end
end
```

**Comment by CameronBieganek** [comment]
That looks good!

Minor point: You could probably replace the instances of `$T` in the error message with literal `"Nothing"`, since the right side will only be evaluated if `T === Nothing`. 🙂

**Comment by CameronBieganek** [comment]
Here's an alternative approach which can handle `Union{Nothing, T}` without throwing an error.

```julia
recursive_fieldtype(T, property::Symbol) = fieldtype(T, property)
function recursive_fieldtype(obj, ex::Expr)
    subex, field = reduce_nested_field(ex)
    return recursive_fieldtype(recursive_fieldtype(obj, subex), field)
end

non_nothing_type(::Type{T}) where T = T
non_nothing_type(::Type{Union{Nothing, T}}) where T = T

function non_nothing_type(::Type{Nothing})
    # This shouldn't normally occur, but just in case somebody implemented a model wrong.
    throw(ArgumentError("Model has a field of declared type `Nothing`. Fix model implementation."))
end

function range2(model::M, field::Union{Symbol, Expr};
                values=nothing, lower=nothing, upper=nothing,
                origin=nothing, unit=nothing, scale::D=nothing) where {M<:Model, D}

    T = non_nothing_type(recursive_fieldtype(M, field))
    if T <: Real && values === nothing
        return numeric_range(T, D, field, lower, upper, origin, unit, scale)
    else
        return nominal_range(T, field, values)
    end
end
```

In action:

```julia
julia> using MLJBase, MLJModels
[ Info: Precompiling MLJModels [d491faf4-2d78-11e9-2867-c94bc002c0b7]
[ Info: Model metadata loaded from registry. 

julia> struct MyModel <: Model
           r::Union{Nothing, Int}
       end

julia> m = MyModel(nothing)
MyModel(
    r = nothing) @984

julia> range(m, :r, lower=1, upper=9)
ERROR: ArgumentError: The inferred hyper-parameter type is Nothing, which is nominal. If this is true, you must specify values=... If this is false, specify the correct type as first argument of `range`, as in the example, `range(Int, :dummy, lower=1, upper=10)`. 
Stacktrace:
 [1] nominal_range(::Type{T} where T, ::Symbol, ::Nothing) at /Users/bieganek/projects/MLJBase.jl/src/hyperparam/one_dimensional_ranges.jl:191
 [2] #range#278 at /Users/bieganek/projects/MLJBase.jl/src/hyperparam/one_dimensional_ranges.jl:96 [inlined]
 [3] top-level scope at REPL[6]:1

julia> MLJBase.range2(m, :r, lower=1, upper=9)
NumericRange(Int64, :r, ... )
```

Unfortunately, my implementation above is not completely robust. Witness:

```julia
julia> pca = @load PCA
PCA(
    maxoutdim = 0,
    method = :auto,
    pratio = 0.99,
    mean = nothing) @776

julia> MLJBase.range2(pca, :mean, lower=1, upper=9)
ERROR: ArgumentError: The inferred hyper-parameter type is Union{Array{Float64,1}, Real}, which is nominal. If this is true, you must specify values=... If this is false, specify the correct type as first argument of `range`, as in the example, `range(Int, :dummy, lower=1, upper=10)`. 
Stacktrace:
 [1] nominal_range(::Type{T} where T, ::Symbol, ::Nothing) at /Users/bieganek/projects/MLJBase.jl/src/hyperparam/one_dimensional_ranges.jl:191
 [2] range2(::MLJModels.MultivariateStats_.PCA, ::Symbol; values::Nothing, lower::Int64, upper::Int64, origin::Nothing, unit::Nothing, scale::Nothing) at /Users/bieganek/projects/MLJBase.jl/src/hyperparam/one_dimensional_ranges.jl:124
 [3] top-level scope at REPL[9]:1
```

This happens because the type of `pca.mean` is `Union{Nothing, T, S}`:

```julia
julia> fieldtype(PCA, :mean)
Union{Nothing, Array{Float64,1}, Real}

julia> MLJBase.non_nothing_type(fieldtype(PCA, :mean))
Union{Array{Float64,1}, Real}
```

**Conclusion:** I wonder if it would be better to expose the `NumericalRange` and `NominalRange` constructors to the user and let them decide which to use? (Instead of using the `range` function.)

**Comment by ablaom** [comment]
Thanks indeed for this excellent feedback. It's a pity @CameronBieganek 's approach based on type-dispatch as opposed to value-dispatch lacks robustness, as it makes a lot of sense. 

It seems there is no one perfect solution. The choices would appear to be:

- (status quo) Live with occassional unexpected (but not unpredictable) behaviour with informative error messages to explain resolution, with some mitigation by discouraging unnecessary union types in model structs

- Split a single method into two harder to remember methods (API breaking)

I propose we stick to the status quo. Am closing but feel free to continue the discussion.

**Comment by CameronBieganek** [comment]
@ablaom @OkonSamuel 

I've been thinking about an idea for another way to create grid searches. I kind of like it, but it's a bit far from the current API. The idea is to have the user provide a function that creates a model given a particular choice of parameters. Basic model types are already functions, so this would work pretty easily for models like `RandomForestClassifier`. Something like this:

```julia
GridSearch(RandomForestClassifier;
    n_trees = [200, 400, 600],
    min_samples_leaf = [1, 5, 10]
)
```

For a pipeline, the user would need to create a function with keyword arguments. Something like this (where I use a hypothetical `Pipeline` constructor):

```julia
function make_rf_pipeline(; n_trees, min_samples_leaf)
    Pipeline(
        OneHotEncoder(),
        RandomForestClassifier(
            n_trees = n_trees,
            min_samples_leaf = min_sample_leaf
        )
    )
end

GridSearch(make_rf_pipeline;
    n_trees = [200, 400, 600],
    min_samples_leaf = [1, 5, 10]
)
```

I was going to suggest using `do` block notation for the pipeline case, but it's probably more natural for the function to use keyword arguments.

Random searches could be created in a similar way:

```julia
RandomSearch(RandomForestClassifier;
    n_trees = DistributionA(...),
    min_samples_leaf = DistributionB(...)
)
```

I envision that the `GridSearch` struct would basically be a wrapper around an array of models. However, this is pretty far from the current API, so it's probably a non-starter. 🙂

**Comment by ablaom** [comment]
@CameronBieganek Thanks for that!

There is an existing tuning strategy called `Explicit` (referenced [here](https://github.com/alan-turing-institute/MLJTuning.jl#implementation-example-search-through-an-explicit-list
)) where you just provide an iterator of models. So, there is already an interface point for the kind I thing you seem to be suggesting, if I understand correctly. 

Here is a simple example of the syntax (taken from [tests](https://github.com/alan-turing-institute/MLJTuning.jl/blob/250c0550168fdf33957e776ebb0b44de04b6fa3c/test/tuned_models.jl#L69)):

```julia
m(K) = KNNRegressor(K=K)
r = [m(K) for K in 2:13]

tm = TunedModel(model=first(r), tuning=Explicit(),
                    range=r, resampling=CV(nfolds=2),
                    measures=[rms, l1], acceleration=accel)

```

The `range` is just any iterator over models of a uniform type, and `model` is just any instance with that type. 

(You can also use this to search of models of varying type but unfortunately you need a dummy wrapper first.)
