### ISSUE TITLE
Remove datasets from MLJBase

### ISSUE THREAD

**Issue by jpsamaroo** [alan-turing-institute/MLJBase.jl#41]
The tagline for MLJBase is "Base code for implementing the MLJ interface for machine learning models". Given that, I was a bit surprised to find that the logic for loading MLJ's built-in datasets was not in MLJ.jl, but was in fact in this package.

I do not believe that including CSV files and other datasets in this package is appropriate, as it adds unnecessary weight to what should be a very small package, and blurs the lines between "MLJ's core API" and "a hodgepodge of stuff to make MLJ convenient for users". Why not create an MLJDatasets.jl package and move the datasets there? If we do that, then we can add as many datasets as we please without worrying that it might cause issues for consumers of MLJ's API.

**Comment by ablaom** [comment]
Thanks for that comment. 

I guess the main reason the datasets are there is: 

- It is convenient when implementing the MLJ model interface to have a couple of data sets available for testing the implementation, without having to manually split data into X and y which RDatasets does not do. 

- As CSV is now an optional dependency, there seems little real practical disadvantage. Contradict me if you disagree.

**Comment by jpsamaroo** [comment]
It should be equally convenient to have them available via MLJDatasets, no? In realistic terms, even if your project only depends on MLJBase, you can still test with MLJDatasets by making it a test dependency.

Having CSV not be a hard dependency is definitely good, but that's now thankfully orthogonal to my concern here (yes, if it were still a hard dep, I'd have even more reason to request its removal).

One other worry is the N+1 case: if datasets are placed in MLJBase, it sets a precedent that other datasets should be PR'd here instead of somewhere more sensible.

**Comment by jpsamaroo** [comment]
I hit Comment too soon, but I wanted to add that I think it just feels plain wrong having datasets in MLJBase, and that is almost my entire argument for moving them elsewhere :)

**Comment by ablaom** [comment]
Thanks for those comments. 

Yes it feel wrong to me too. However, from the practical point-of-view, shifting things out to new repo achieves only one thing, as far as I can tell: One more repo to administer and keep synchronized.
