### ISSUE TITLE
Release that doesn't have ScientificTypes as a hard dep?

### ISSUE THREAD

**Issue by DilumAluthge** [alan-turing-institute/MLJBase.jl#412]
`MLJBase#dev` no longer has ScientificTypes as a hard dep. Would it be possible to get a release with this in it? 

Then, I'll be able to use the latest MLJBase plus the latest MLJScientificTypes, and this will be compatible with ScientificTypes 1.0.

(The current latest release of MLJBase cannot be installed alongside ScientificTypes 1.0.)

**Comment by ablaom** [comment]
Why do you want to use ScientificTypes 1.0? The main difference is `scitype(nothing)` is now `Nothing` instead of `Unknown`, which breaks MLJBase, but not in ways that would effect your development, I would have thought.

**Comment by DilumAluthge** [comment]
> Why do you want to use ScientificTypes 1.0? The main difference is `scitype(nothing)` is now `Nothing` instead of `Unknown`, which breaks MLJBase, but not in ways that would effect your development, I would have thought.

I don't actually have a dependency on ScientificTypes.jl, but I ran into compat issues when trying to use the latest registered release of MLJBase with the latest registered release of MLJModelInterface.

Specifically, MLJModelInterface 0.3.5 requires ScientificTypes 1.0.0. 

Although.... I think I don't actually need MLJModelInterface 0.3.5. I think for my purposes, MLJModelInterface 0.3.4 is sufficient.

But yeah, if someone wants to use MLJModelInterface 0.3.5, they need ScientificTypes 1.0.0.

**Comment by DilumAluthge** [comment]
I can confirm that MLJModelInterface 0.3.4 is sufficient for my use case.

**Comment by ablaom** [comment]
Great. FYI A new minor release of MLJBase is imminent.
