### ISSUE TITLE
decode returns Any

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJBase.jl#42]
when dealing with sklearn classifiers I was basically doing

```julia
yplain = MLJBase.int(y)
decode = MLJBase.decoder(y[1])
```

and then using the `decode` in predict

```
return decode(preds)
```

where the preds are output from Sklearn.predict

I was surprised that in a simple example where `y` is a `CategoricalArray{String}`, the output of `predict` is  `Any` whereas it should have been `String` (and in fact the elements of the predict are Strings as they should be)

To clarify a  bit:

```julia
julia> y[1:3]
3-element CategoricalArray{String,1,UInt32}:
 "A"
 "B"
 "A"
julia> m = DummyClassifier();
julia> f, _, _ = fit(m, 1, X, y);
julia> p = predict(m, f, X)
100-element Array{Any,1}:
 "B"
 "B"
 "A"
...
 ```

did I do something wrong or is this by design?

PS: it's odd because I'm using the same code than is used in `SVM` as far as I can tell; however using `SVClassifier` on the example above returns 

```
100-element Array{CategoricalString{UInt32},1}:
 "A"
 "B"
 "A"
```

**Comment by ablaom** [comment]
Something's not right here. The prediction element type (what you get when you do yhat[1])  should be the same as the type for training. In the dummy example this should be `CategoricalString` not `String`.  

Did you sort this?

**Comment by tlienart** [comment]
Yes, apologies for the spam, it's a bit trickier to debug the model importing macros so I wasn't seeing clearly but after comparing `svm` and what I had written I saw that an issue was with how I was obtaining the decoder (effectively unrelated to what I wrote in this message); I had a test like

```julia
if eltype(y) isa CategoricalString
# retrieve decoder
```

but that's never true, it should have been `if eltype(y) <: CategoricalString`, this error often bites me...
