### ISSUE TITLE
Log probability?

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJBase.jl#43]
This may have already been discussed somewhere; sklearn provides a `predict_log_proba` is this relevant for us or should we just ignore it?

**Comment by ablaom** [comment]
I suggest we ignore it. If only a `predict_log_proba` exists, then broadcast `exp` to get the raw probability. We could add a `predict_log_proba` fallback in MLJBase, but no-one has requested this yet.

**Comment by tlienart** [comment]
I think there's a question of accuracy (often log prob will be more accurate) but ok sure we can wait to see a use-case. Both are always present in pair.
