### ISSUE TITLE
log_cosh distance overflow

### ISSUE THREAD

**Issue by pfarndt** [alan-turing-institute/MLJBase.jl#437]
The current implementation of the log_cosh measure overflows quite soon:

```julia
julia> using MLJ, MLJBase

julia> log_cosh([0], [712])
1-element Array{Float64,1}:
 Inf
```

Somewhere I found this implementation, which circumvents the computation of the `cosh` responsible for the overflow:

```
softplus(x::Real) = ifelse(x > 0, x + log1p(exp(-x)), log1p(exp(x)))
logcosh(x::T) where T = x + softplus(-2x) - log(convert(T, 2))
```

See also https://github.com/JuliaML/LossFunctions.jl/issues/136#issue-678609059

**Comment by ablaom** [comment]
@pfarndt Thanks for reporting. Any volunteers to pick this up? @ven-k @ludoro @OkonSamuel . Looks straightforward.

**Comment by ablaom** [comment]
Assigned to @ven-k. Thanks!!
