### ISSUE TITLE
schema is too slow

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJBase.jl#48]
This may be an issue with https://github.com/alan-turing-institute/ScientificTypes.jl/issues/12 

In this example it takes a whopping 30 seconds to get... this is stupid and it slows down the `fit` method of some of the MLJModels interface we have a ton indeed, for instance in GLM we do

```
features = MLJBase.schema(X).names
```

on the following example, it takes 30 seconds on my machine to get this

```
using MLJBase
X = MLJBase.table(randn(100_000, 50));
@time MLJBase.schema(X).names
29.473154 seconds (1.86 M allocations: 168.313 MiB, 0.11% gc time)
```

I understand the issue may be trickier than it seems.

In any case I'll modify  all such lines in MLJModels to use `Tables.schema` instead of `MLJBase.schema`

**Comment by ablaom** [comment]
resolved in pending ScientificTypes release 0.2.2 https://github.com/JuliaRegistries/General/pull/4439
