### ISSUE TITLE
Problems interfacing with MLJ from an external package

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJBase.jl#58]
Writing an interface externally does not exactly seem to be a smooth procedure

I'm doing this for `MLJLinearModels` currently and am running in quite a few issues the most annoying of all being that I can't seem to use `metadata_*`

```julia
module Package
import MLJBase
# ...
MLJBase.metadata_pkg(...)
end
```

```julia-repl
using Package
[ Info: Precompiling MLJLinearModels [6ee0df7b-362f-4a72-a706-9e79364fb692]
WARNING: eval into closed module MLJBase:
Expr(:block, #= Symbol( ...
```

This is an issue with `eval`... (question on discourse:  https://discourse.julialang.org/t/use-of-eval-in-closed-module-and-incremental-compilation-may-be-broken/30028)

Another issue is that adding the `import MLJBase` in the module **quadruples the precompilation time** of the module even though just loading it in the  REPL is not that slow...? 

(without: `7.6` seconds pre-compilation time, with: `37.2` seconds)

It would be a good to write a dummy model repo and interface with it cleanly analyzing what may be causing issues as this situation is not ideal... If anything it will help us show an example of how people can  interface with MLJ in the future.

I'll hold back from developping the interface for MLJLM  while we figure these things out

**Comment by tlienart** [comment]
Ok after much time wasted with trial and error I actually found a solution for the first problem, just use `parentmodule(T).eval(ex)` this fixes the issue; I'll open a PR tomorrow (it's close to 2am here)
second issue stays but that one can be worked on in the  longer term

**Comment by ablaom** [comment]
> Another issue is that adding the import MLJBase in the module quadruples the precompilation time of the module even though just loading it in the REPL is not that slow...?

> (without: 7.6 seconds pre-compilation time, with: 37.2 seconds)

@tlienart I wonder is this still an issue after the dependency changes?

**Comment by tlienart** [comment]
It's much much better; 

Julia nightly --> 11.9s
Julia 1.2 --> 6.5s

I think the slowdown on nightly due to CatArray is still not fully fixed but hopefully will be.
