### ISSUE TITLE
Add performance measures from MLBase

### ISSUE THREAD

**Issue by OkonSamuel** [alan-turing-institute/MLJBase.jl#60]
Would there be any need to export MLBase performance evaluation measures like confusion matrix, true and false negative rates, ROC etc. from MLJBase or would it be better using them from MLBase.

**Comment by tlienart** [comment]
Hello @OkonSamuel ! thanks for your help, there is definitely need for such things and I believe @vollmersj has already started looking at it. 

@vollmersj maybe you could list what you've already done / what's up for grabs / what you'd need help with?

Cheers

**Comment by ablaom** [comment]
https://github.com/alan-turing-institute/MLJ.jl/issues/277

**Comment by tlienart** [comment]
Most of it  was done in  #88,  there's still things up for  grabs in #95
