### ISSUE TITLE
ScientificTypes.TRAIT_GIVEN_FUNCTION not updating; info(rms) broken

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJBase.jl#85]
```julia
julia> info(rms)
ERROR: MethodError: no method matching info(::MLJBase.RMS, ::Val{:other})
Closest candidates are:
  info(::Any) at /Users/anthony/Dropbox/Julia7/MLJ/MLJBase/src/MLJBase.jl:188
  info(::Any, ::Val{:measure}) at /Users/anthony/Dropbox/Julia7/MLJ/MLJBase/src/measures.jl:91
Stacktrace:
 [1] info(::MLJBase.RMS) at /Users/anthony/Dropbox/Julia7/MLJ/MLJBase/src/MLJBase.jl:188
 [2] top-level scope at none:0
```

Remedy: put ScientificTypes.TRAIT_GIVEN_FUNCTION updates back into __init__

(baby went out with the bathwater in last patch 😢)

**Comment by tlienart** [comment]
if we can we should avoid the use of __init__, can this not be achieved otherwise?

**Comment by ablaom** [comment]
Sorry, I did not see this comment before proceeding. 

There's no simple way to avoid the __init__. One package is updating a global variable defined in another package. 

I don't think __init__ is necessarily hacky. The issues we have had in the past are to do with `eval` in  `__init__`. That is not the case here.

If it is really an issue, I will look into an alternative approach. Can you confirm this really is an issue?

I've included a test that catches the trip-up.
