### ISSUE TITLE
Use levels in classes and alternative def for `int`

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJBase.jl#90]
See https://github.com/JuliaData/CategoricalArrays.jl/issues/220 for context. 

Summarized comments from Milan:

1. the definition of `classes` would better avoid accessing internal fields
1. the sentence "_In particular, while x in classes(x) is always true, x in x.pool.levels is not true._" in the docstring is incorrect, as categorical values compare equal to their unwrapped equivalent. So I'm not sure why classes is needed.
1. suggestion is to use `levels` for/in `classes` 
1. simplify `int` to `int(x::CategoricalElement) = CategoricalArrays.order(x.pool)[x.level]`

**Comment by tlienart** [comment]
For the sake of completeness:

```julia
a = categorical([:a,:b,:c,:a,:b]);
:a in levels(a) # true
:a in levels(a[1].pool) # true
a = categorical(collect("asfasdfasdfasdfasdf"))
'a' in levels(a) # true
```

etc.

**Comment by ablaom** [comment]
@tlienart @nalimilan Thanks indeed for the comments.

I will implement the docstring suggestions, and code improvements after testing.

The short answer to the `classes` vs `levels` question is: "I do need `classes`". 

The long answer is: Initially, I decided, after much agonising, that I really did need `classes`. The reasons are .... However, it's *possible* that a lengthy code review taking recent changes to CategoricalArrays behaviour into account (broadcasting, and so forth), would show that `classes` are not needed, and maybe I'll get around to this one day...." 😫
